---
title: "Advanced R Programming"
author: Jeffrey Spinner
copywrite: 2018
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
*Insert Chunk*  *Ctrl+Alt+I*.
*Preview* *Ctrl+Shift+K* .


```{r}
setwd("D:\\R_Programs_wd\\R_Programming to Git\\Advanced R")  # Notice \\, need for each time if 
                            # more than one folder deep

fin <- read.csv("D:\\R_Programs_wd\\Future-500.csv")

head(fin)
tail(fin, 10)   # Can check any arbitrary number of lines, e.g., 10

str(fin)
summary(fin)

```


```{r}
# Data Wrangling: Changing from a non-factor to a factor

fin$ID <- factor(fin$ID)                  # ID was just a row identifier.
fin$Inception <- factor(fin$Inception)    # Inception was year of corp creation, a catagorical variable.
str(fin)
summary(fin)
```



```{r}
# Data Wrangling: Changing a factor into correct data type

# Factor Variable Trap (FVT)

# Converting into Numerics for Characters not an issue...

a <- c("12", "13", "14", "12", "19")
b <- as.numeric(a)
b

```

```{r}
# Factor Variable Trap (FVT)

# Converting into Numerics for Factors

z <- factor(c("12", "13", "14", "12", "19"))
z   #Kinda looks like a number vector, but it is NOT.
```

```{r}
y <- as.numeric(z)
y   # Just picked up the levels of each factor!
```
```{r}
z <- factor(c("12", "13", "14", "12", "19"))
x <- as.numeric(as.character(z))
x
typeof(x)
```

```{r}
#FVT Example

fin$Profit <- factor(fin$Profit)
str(fin)
fin$Profit <-as.numeric(as.character(fin$Profit))
str(fin)
```

```{r}
#FVT
# sub() and gsub(), gsub() replaces all, sub() only first instance

closeAllConnections()
rm(list=ls())
my_vars <- c("Revenue", "Expenses")

fin <- read.csv("D:\\R_Programs_wd\\Future-500.csv")
head(fin[my_vars])
fin$Expenses <- gsub(" Dollars","",fin$Expenses)
head(fin[my_vars])
fin$Expenses <- gsub(",","",fin$Expenses)
head(fin[my_vars])

typeof(fin$Expenses)  # gsub converts factors into characters.

fin$Expenses <- as.numeric(fin$Expenses)

typeof(fin$Expenses)

```
```{r}
# Factor to numeric for Revenue variable in dataset

rm(list=ls())

my_vars <- c("Revenue", "Growth")

fin <- read.csv("D:\\R_Programs_wd\\Future-500.csv")

head(fin[my_vars])

fin$Revenue <- gsub("\\$","",fin$Revenue)
head(fin[my_vars])

fin$Revenue <- gsub(",","",fin$Revenue)
head(fin[my_vars])

fin$Revenue <- as.numeric(fin$Revenue)

typeof(fin$Revenue)


fin$Growth <- gsub("\\%","",fin$Growth)

fin$Growth <- as.numeric(fin$Growth)
head(fin[my_vars])

typeof(fin$Growth)
summary(fin[my_vars])
```

```{r}
# Dealing with Missing Data (NA) and empty values
fin <- read.csv("D:\\R_Programs_wd\\Future-500.csv")  # , na.strings=c("", "<NA>") <NA> is treated as NA

# complete.cases(fin)       # A logical vector of TRUE and FALSE, TRUE if all values

fin[!complete.cases(fin),]  # All rows NOT complete (Only NAs) with all columns (variables)\
                            # Not empty values or strings like "\\$", "," etc <NA> is treated as NA (dup)
rm(list=ls())
fin <- read.csv("D:\\R_Programs_wd\\Future-500.csv", na.strings=c(""))
                            # Replaces on import character strings with NA
fin[!complete.cases(fin),]




```

```{r}
# Filtering: using which() for non-missing data
rm(list=ls())
fin <- read.csv("D:\\R_Programs_wd\\Future-500.csv", na.strings=c(""))
fin$Revenue <- gsub("\\$","",fin$Revenue)
fin$Revenue <- gsub(",","",fin$Revenue)

head(fin)
fin$Revenue == 9746272

fin[fin$Revenue == 9746272,]  # Produces 3 outputs with 2 NA rows because that record 
                              # contained some missing data...so doesn't know what to do.

# which only returns TRUE values.

fin[which(fin$Revenue == 9746272),]
# Viola

fin[which(fin$Employees == 45),]

```

```{r}
# Filtering: using is.na() for missing data
 
# Ex.: fin[fin$Expenses == NA,] returns a vector of all NAs  (any logical comparison to NA is NA T == 
# NA is NA, F == NA is NA, NA == NA is NA)


# closeAllConnections()

rm(list=ls())
fin <- read.csv("D:\\R_Programs_wd\\Future-500.csv", na.strings=c(""))
# Something weird is going on with "<NA>" R is reading it as NA...

fin$Expenses
is.na(fin$Expenses) # Shows where a;; the NAs are...
head(fin, 25)

fin[is.na(fin$Expenses),]

fin[is.na(fin$State),]
```
```{r}
# Removing records with missing data (BAD IDEA)
rm(list=ls())
fin <- read.csv("D:\\R_Programs_wd\\Future-500.csv", na.strings=c(""))
fin_backup <- fin   # Always work on backup of actual data set.

fin[!complete.cases(fin),]
fin[!is.na(fin$Industry),]  # Gives you all the records with only complete data
fin <- fin[!is.na(fin$Industry),]
head(fin, 30)

# verify we dealt with all industry cases
fin_backup[!complete.cases(fin_backup),]
fin[!complete.cases(fin),]
```





```{r}
# Resetting the dataframe index
# rm(list=ls())
# fin <- read.csv("D:\\R_Programs_wd\\Future-500.csv", na.strings=c(""))
# fin_backup <- fin  

new_fin<- fin
new_fin[!is.na(new_fin$Industry),]  # Prints dataset with removed rows

rownames(new_fin) <- 1:nrow(new_fin)# Reorders rows but not efficient
head(new_fin, 30)

new_fin<-fin
rownames(new_fin)<-NULL             # Reorders rows efficiently
head(new_fin, 30)


```

```{r}
# Replacing Missing Data: Factual Analysis (can actually regen missing data) ffs
rm(list=ls())
fin <- read.csv("D:\\R_Programs_wd\\Future-500.csv", na.strings=c(""))

backup_fin <- fin

fin[!complete.cases(fin),]

fin[is.na(fin$State) & fin$City == "New York",] # finds all New York cities without NY as state, i.e., NA

fin[is.na(fin$State) & fin$City == "New York", "State"] <- "NY" # won't print out...

# Check:

fin[c(11,379),]

# Left to deal with:

fin[!complete.cases(fin),]

fin[is.na(fin$State) & fin$City == "San Francisco", "State"] <- "CA"

fin[c(84,267),]
```

```{r}
# Replacing Missing Data: Median Imputation Method 
rm(list=ls())
fin <- read.csv("D:\\R_Programs_wd\\Future-500.csv", na.strings=c(""))

backup_fin <- fin

fin[!complete.cases(fin),]

median(fin[fin$Industry == "Retail", "Employees"], na.rm = T)

# Best Practices 
med_empl_retail <- median(fin[fin$Industry == "Retail", "Employees"], na.rm = T)

fin[is.na(fin$Employees) & fin$Industry == "Retail", "Employees"] <- med_empl_retail

fin[fin$Employees==28 & fin$Industry == "Retail",]

```

```{r}
rm(list=ls())
fin <- read.csv("D:\\R_Programs_wd\\Future-500.csv", na.strings=c(""))

# head(fin, 30)
backup_fin <- fin

# fin <- fin[!is.na(fin$Industry),]
# fin

fin$Growth <- gsub("%","",fin$Growth)

fin$Growth <- as.numeric(fin$Growth)

median_growth_constr <- median(fin[fin$Industry == "Construction", "Growth"], na.rm = T)


# fin[is.na(fin$Growth),]

median_growth_constr->fin[is.na(fin$Growth) & fin$Industry=="Construction", "Growth"] 
fin[8,]
```

