---
title: "R Notebook"
output: html_notebook
---



```{r}
library(ggplot2)
library(ggpmisc)
library(colorspace)
library(tidyr)
library(mgcv)
library(RColorBrewer)
library(wesanderson)
library(MASS)
names(Boston)

lm.Experiment <- lm(medv ~ lstat, data = Boston)
lm.Experiment2 <- lm(medv ~ lstat +I(lstat^2), data = Boston) 
#Notice "I(lstat^2)" the "I" is required or it just fits a regular lm(medv~lstat, data=Boston)
lm.Experiment3 <- lm(medv ~ lstat + I(lstat^2) + I(lstat^3), data = Boston)
lm.Experiment4 <- lm(medv ~ lstat + I(lstat^2) + I(lstat^3) + I(lstat^4), data = Boston)

summary(lm.Experiment)
plot(lm.Experiment, which = 1:6)
p.exper <- ggplot(Boston, aes(x=lstat, y=medv))+
  geom_point(aes(color=lstat))+
  scale_colour_gradientn(colours = terrain.colors(3))+
  geom_smooth(color="red", method = lm)+ # Forces a linear regression fit.  lm=medv~lstat does not!  It gives the polynomial fit.
  ylim(0,50)+
  labs(title="Linear Regression", x="Low SES", y="Median House Valuation", color="Low SES", caption = "(based on data from Boston Database)")+
  theme(plot.title = element_text(hjust=0.5))
p.exper


summary(lm.Experiment2)
plot(lm.Experiment2, which = 1:6)
p.exper2 <- ggplot(Boston, aes(x=lstat, y=medv))+
  geom_point(aes(color=lstat))+
  scale_colour_gradientn(colours = terrain.colors(3))+
#  geom_smooth()+
  stat_smooth(method = "lm", formula = y~poly(x,2), size = 1)+
  ylim(0,50)+
  stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), formula = formula2, parse = TRUE, eq.with.lhs = "italic(hat(y))~`=`~", label.x = 25)+
  labs(title="2nd Degree Polynomial Regression", x="Low SES", y="Median House Valuation", color="Low SES", caption = "(based on data from Boston Database)")+
  theme(plot.title = element_text(hjust=0.5))
p.exper2

summary(lm.Experiment3)
plot(lm.Experiment3, which = 1:6)
p.exper3 <- ggplot(Boston, aes(x=lstat, y=medv))+
  geom_point(aes(color=lstat))+
  scale_colour_gradientn(colours = terrain.colors(3))+
#  geom_smooth(color="grey")+  This works
  stat_smooth(method = "lm", formula = y ~ poly(x,3), size=1)+
# stat_smooth not plotting.
  ylim(0,50)+
  labs(title="3rd Degree Polynomial Regression", x="Low SES", y="Median House Valuation", color="Low SES", caption = "(based on data from Boston Database)")+
  theme(plot.title = element_text(hjust=0.5))
p.exper3

summary(lm.Experiment4)
plot(lm.Experiment4, which = 1:6)
p.exper4 <- ggplot(Boston, aes(x=lstat, y=medv))+
  geom_point(aes(color=lstat))+
  scale_colour_gradientn(colours = terrain.colors(3))+
#  geom_smooth(color="grey")+  This works
  stat_smooth(method = "lm", formula = y ~ poly(x,4), size=1)+
# stat_smooth not plotting...had to use "y" and "x" not variable labels...ffs
  ylim(0,50)+
  labs(title="4th Degree Polynomial Regression", x="Low SES", y="Median House Valuation", color="Low SES", caption = "(based on data from Boston Database)")+
  theme(plot.title = element_text(hjust=0.5))
p.exper4

formula1 <- y ~ x
formula2 <- y ~ poly(x,2)
formula3 <- y ~ poly(x,3)
formula4 <- y ~ poly(x,4)

formulas <- c(formula1, formula2, formula3, formula4)

p.experAll <- ggplot(Boston, aes(x=lstat, y=medv))+
  geom_point(aes(color=lstat))+
  scale_colour_gradientn(colours = terrain.colors(3))+
  stat_smooth(method = "lm", formula = y ~ x, size = 1, color="blue", se=F)+
  stat_smooth(method = "lm", formula = y ~ poly(x,2), size = 1, color="green", se=F)+
  stat_smooth(method = "lm", formula = y ~ poly(x,3), size= 1, color="mediumorchid2", se=F)+  
  stat_smooth(method = "lm", formula = y ~ poly(x,4), size= 1, color="cyan", se=F)+
#  geom_smooth(color="grey")+
  ylim(0,50)+
  stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")),formula = formula1, eq.with.lhs = "italic(hat(y))~`=`~", parse = TRUE, label.x = 25, color="blue")+
  stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), formula = formula2, parse = TRUE, eq.with.lhs = "italic(hat(y))~`=`~", label.y = 40, label.x = 25, color="green")+
  stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), formula = formula3, parse = TRUE, eq.with.lhs = "italic(hat(y))~`=`~", label.y = 32, label.x = 25, color="mediumorchid2")+
  stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), formula = formula4, parse = TRUE, eq.with.lhs = "italic(hat(y))~`=`~", label.y = 1, label.x= 20, color="cyan")+
  
  labs(title="All Regression Functions", x="Low SES", y="Median House Valuation", color="Low SES", caption = "(based on data from Boston Database)")+
  theme(plot.title = element_text(hjust=0.5))
p.experAll

```
```{r}
# Step Functions for Overfit Potential Datasets.
library(ggplot2)
library(ggpmisc)
library(colorspace)
library(tidyr)
library(MASS)
names(Boston)

People <- "cyan2"
plot <- ggplot(Boston, aes(x = lstat, y=medv))+
  geom_point(aes(color="People"), size=1.75, pch=36)+
  stat_smooth(method = "lm", formula = y ~ cut(x, breaks = c(-Inf, 5, 10, 15, 20, Inf)))+
  labs(title="Step Function", x="Low SES %", y="Median House Value ($1,000's)", caption = "(based on data from Boston Database)")+
  theme(plot.title = element_text(hjust=0.5))+
#  theme(legend.position="none")  Doesn't work here, works on other graph below!


stepPlot

#Can't remove the freakin legend...

```
```{r}
library(SemiPar)
library(ggplot2)
library(ggpmisc)
library(colorspace)
data(onions)
attach(onions)

onion.plot <- ggplot(onions, aes(x=dens, y=yield))+
  theme(plot.title = element_text(hjust=0.5), legend.position="none")+
  geom_point(aes(color="palegreen3"), size=2.5, pch=111)+
  stat_smooth(method = "lm", formula = y ~ poly(x,1), se=F, color="brown3")+
  stat_smooth(method = "lm", formula = y ~ poly(x,2), se=F, color="orchid3")+
  stat_smooth(method = "lm", formula = y ~ poly(x,3), se=F, color="lightsteelblue3")+
  labs(x="Density", y="Yield", title="Yield v. Density (Linear, 2nd Order, 3rd Order)")+
  annotate("segment", x = c(125,175), xend = c(147,180), y = c(125,125), yend = c(65,62), colour = c("lightsteelblue3","orchid3"), size=0.8, alpha=0.6, arrow=arrow())+
  annotate("text", x = c(125,175), y = c(135,135), label = c("3rd Order", "2nd Order") , color=c("lightsteelblue3", "palevioletred3"), size=4 , angle=0, fontface="bold")
  
         

onion.plot
```

